### ISSUE TITLE
Bug: test host in the run targets

### ISSUE THREAD

**Issue by CognitiveDisson** [MobileNativeFoundation/rules_xcodeproj#2990]
### Description

If a test target specifies a test host, then in the scheme for that test target, the test host must be included in the list of targets to be built for testing and not for run.

### Reproduction steps

You can reproduce this bug in the example project.
![Screenshot 2024-04-04 at 15 39 38](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/10621118/4a13b9fe-8a5a-4303-a68c-cb726ce4e992)

### Expected behavior

Test host builded only when you running tests.

### rules_xcodeproj version

fca6cfba49a6f75917c2b8b0143263a7dea2d46b

### Xcode version

15.1

### Bazel version

7.1.0

**Comment by brentleyjones** [comment]
The test host isn't being added there because of the test, it's because of `adjust_schemes_for_swiftui_previews`. The test host is built without being listed in the scheme. When you change the example to have `adjust_schemes_for_swiftui_previews = False`, you'll see no test host in the scheme, but it still builds the test host when running tests.
